# Generated by Django 2.0.2 on 2018-03-02 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180302_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=False, to='orders.OrderInfo', verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='sku',
            field=models.ForeignKey(on_delete=False, to='goods.GoodsSKU', verbose_name='订单商品'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='address',
            field=models.ForeignKey(on_delete=False, to='users.Address', verbose_name='收获地址'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL, verbose_name='下单用户'),
        ),
    ]
